### ISSUE TITLE
一个编程菜鸡的咨询

### ISSUE THREAD

**Issue by jackyliu16** [atticus-lv/simple_node_tree#1]
昂，比较想知道这个程序大概是如何跑起来的...
有点想将其作为一个简单的思维导图程序，但是似乎出现了点问题，具体如下：
1. 通过对于你所给出的代码进行分析，得到里面所出现的import bdy是blender中解释器所特有的模块之后，通过blender打开文件...
2. 然后这个编译器似乎没有办法将我所下载的文件放置于环境当中，因而...?

**Comment by atticus-lv** [comment]
emmmm, 你把他作为一个插件安装上去才行
